### PR TITLE
refactor: use slack's internal markdown converter

### PR DESCRIPTION
**Pull request by nobe4**
This is a companion PR that goes with
https://github.com/rneatherway/slack/pull/4 to showcase what changes will look like in the gh-slack client.

It keeps the code as untouched as possible, and cleans the obsolete functions/types.

The code currently uses the latest commit on https://github.com/rneatherway/slack/pull/4 and will need to be updated accordingly if/when that PR is merged.

Current version fetched with:
```
go get github.com/rneatherway/slack@d41e05cbe802da709eba14bffd8d6bf3716aa0d9
```

### CODE REVIEW

**Comment by rneatherway** [comment]
These changes look good to me :smile: 

Feel free to merge when ready.

**Comment by nobe4** [comment]
Thanks @rneatherway! It seems that by updating to a specific commit, I've polluted the go.mod file. Maybe we can create a release of `slack`? That might fix this?

Any thoughts?

**Comment by rneatherway** [comment]
> Thanks @rneatherway! It seems that by updating to a specific commit, I've polluted the go.mod file. Maybe we can create a release of `slack`? That might fix this?

What do you mean when you say that you've polluted it? I don't have any trouble running the tests locally on this PR.

**Comment by nobe4** [comment]
I meant to say that the go.mod got a bunch of duplicate lines from installing the various commits by hands.

I don't really know if it's problematic but it looks unnecessary 🧐

**Comment by rneatherway** [comment]
Ah! I see what you mean now. Try running `go mod tidy` - that should clear it up :smile:

**Comment by nobe4** [comment]
Indeed! Thanks 🙏

**Pull request merged**
