### PR TITLE
Extract core client functionality

### PR DESCRIPTION
**Pull request by rneatherway**
The core client functionality has been extracted to a new repository at https://github.com/rneatherway/slackclient. This comprises two pieces of functionality:

1. `GetAuth` for getting the Slack token and cookies if you don't want to use the built-in client. I don't know that anyone wants to do this yet, but it seems like a reasonable thing to want to do.
2. `New` for creating a new client populated with those authentication details and an `API` method for calling the Slack API.

Other thoughts:

* Somewhat ugly is that we now have two `slackclient` packages and the `SlackClient` in this repository just wraps one from the other repository.
* I was thinking that perhaps the other repository should just have a `slack` package with `slack.GetAuth(...)` and `slack.NewClient(...)`. That reads more cleanly to me.
* I do think `API` should probably take a context for future-proofing.
* In one or both repositories I would like to provide a way of short-cutting the cookie (and possibly token) fetching so that

### CODE REVIEW

**Comment by nobe4** [comment]
Happy new year 👋 

- > GetAuth for getting the Slack token and cookies [...] it seems like a reasonable thing to want to do.
  
  Agreed 👍

- `slackclient.SlackClient` is a bit ugly I agree, `slack.Client`, `slack.NewClient`, and `slack.GetAuth` would read better.

- > I do think API should probably take a context for future-proofing.

  Agreed 👍 

- > In one or both repositories I would like to provide a way of short-cutting the cookie (and possibly token)

  I like this idea as well.

- `Auth` should probably be updated to support as well the "usual" slack tokens as described in https://api.slack.com/authentication/token-types

  How about something like:
  ```go
  client := slack.NewClient("my-team")
  
  // this
  if err := client.AuthWithCookies(); err != null {
    return err
  }
 
  // or that
  if err := client.AuthWithToken("the-token"); err != null {
    return err
  }
  ```

  This would internally call `GetCookieAuth` (exported method) or `GetTokeAuth` that are available for direct use if needed.

**Comment by rneatherway** [comment]
> * `slackclient.SlackClient` is a bit ugly I agree, `slack.Client`, `slack.NewClient`, and `slack.GetAuth` would read better.

Done

> * > I do think API should probably take a context for future-proofing.
>   Agreed 👍

Done

> * > In one or both repositories I would like to provide a way of short-cutting the cookie (and possibly token)
>   I like this idea as well.

I haven't done this yet, I think it can wait for a follow-up. The motivation is that it's annoying to iterate on MacOS because you are prompted for every new binary when it accesses the keychain.


> * `Auth` should probably be updated to support as well the "usual" slack tokens as described in https://api.slack.com/authentication/token-types
>   How about something like:
> ...

This is an interesting idea. It might actually allow removing `Null` because half the reason that method exists is to _not_ call `GetAuth(...)`. An addition of a `WithHTTPClient(...)` method would then allow providing the stub `RoundTripper`.

I'm a bit unsure what your proposed `GetTokenAuth(...)` method would look like though. Would it still have to get the cookie and then just use the token given to it? For all token types?

```golang
func GetTokenAuth(token string) (*Auth, error) {
	cookie, err := config.GetCookie()
	if err != nil {
		return nil, err
	}

	return &Auth{Token: string(matches[1]), Cookies: map[string]string{"d": cookie}}, nil
}
```

**Comment by nobe4** [comment]
> The motivation is that it's annoying to iterate on MacOS because you are prompted for every new binary when it accesses the keychain.

Yeah, I felt that when doing testing as well.

> I'm a bit unsure what your proposed GetTokenAuth(...) method would look like though. Would it still have to get the cookie and then just use the token given to it? For all token types?

A ~~picture~~ PR is worth a thousand words: https://github.com/rneatherway/slackclient/pull/1
It'll need some more work to make sure passing a token directly actually works, but my past experience tells me it would.


> An addition of a `WithHTTPClient(...)` method would then allow providing the stub RoundTripper.

👍 
PR'ed in https://github.com/rneatherway/slackclient/pull/2

**Comment by rneatherway** [comment]
OK, I've made the rest of those changes across the two repositories and done a little tidying. The only last thing I think I want to do here is to rename `rneatherway/slackclient` to just `rneatherway/slack` to avoid the awkward package renaming.

Any other thoughts before we tidy this up?

**Comment by nobe4** [comment]
Sounds good! Nothing else worthy to add here :)

**Pull request merged**
